import type { Metadata } from "next";
import localFont from "next/font/local";

import SideNav from "./components/nav/nav";
import Header from "./components/header/header";

import "./globals.css";
import styles from './layout.module.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Impact interview",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const API_URL = process.env.API_URL;
  const data = await fetch(`${API_URL}/products/categories`)
  const categories = await data.json();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header categories={categories} />
        <div className={styles.mainContainer}>
          <SideNav categories={categories} />
          <div className={styles.contentContainer}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
